# authors:
# David Hernandez Lopez, david.hernandez@uclm.es
import os
import sys

current_path = os.path.dirname(os.path.realpath(__file__))
# sys.path.append(os.path.join(current_path, '..'))
# sys.path.insert(0, '..')

processes_path = os.path.normpath(os.path.dirname(current_path) + '/processes')
# GDAL_PATH = "gdal"
# CGAL_PATH = "cgal"
LIB_PATH = "lib" # library processes
processes_providers = []
# processes_providers.append(GDAL_PATH)
# processes_providers.append(CGAL_PATH)
processes_providers.append(LIB_PATH)


PROCESS_FUNCTION_EXPORT_PROJECT_TO_GEOPACKAGE = "Export Project to GeoPackage"
PROCESS_FUNCTION_EXPORT_PROJECT_TO_GEOPACKAGE_PARAMETER_GEOPACKAGE = "GeoPackage"

PROCESS_FUNCTION_PUBLISH_LAYERS_SET_NAME = "Publish layers set"
PROCESS_FUNCTION_PUBLISH_LAYERS_SET_PARAMETER_UPLOAD_FOLDER = "Upload folder"
PROCESS_FUNCTION_PUBLISH_LAYERS_SET_PARAMETER_LAYERS_SET = "Layers Set"
PROCESS_FUNCTION_PUBLISH_LAYERS_SET_PARAMETER_NAME = "Name"
PROCESS_FUNCTION_PUBLISH_LAYERS_SET_LAYER_PARAMETER_FILE_PATH = "file_path"
PROCESS_FUNCTION_PUBLISH_LAYERS_SET_LAYER_PARAMETER_LAYERS = "layers"
PROCESS_FUNCTION_PUBLISH_LAYERS_SET_LAYER_PARAMETER_LABEL = "label"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_NAME = "Layer name"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_NAME = "filepath"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_TITLE = "Title"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_TITLE = "title"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_POSITION = "Position"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_POSITION = "position"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_CRS = "CRS"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_CRS = "crs"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_DATE = "Date"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_DATE = "date"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_MINIMUM_ZOOM = "Minimum zoom"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_MINIMUM_ZOOM = "minzoom"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_MAXIMUM_ZOOM = "Maximum zoom"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_MAXIMUM_ZOOM = "maxzoom"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_LAYER_STYLE = "Layer style"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_LAYER_STYLE = "sldpath"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_TYPE = "Layer type"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_TYPE = "type"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_TYPE_VECTOR = "vector"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_TYPE_VECTOR = "vector_layer"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_TYPE_RASTER = "raster"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_TYPE_RASTER = "orthomosaic"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_DESCRIPTION = "Description"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_DESCRIPTION = "description"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_VISIBLE = "Visible"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_VISIBLE = "visible"
PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_GROUP_NAME = "Layers group name"
PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_GROUP_NAME = "groupname"
# PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_GROUP_NAME = "group_id"
process_publish_layer_target_tag_by_source_tag = {}
process_publish_layer_target_tag_by_source_tag[PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_NAME] \
    = PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_NAME
process_publish_layer_target_tag_by_source_tag[PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_TITLE] \
    = PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_TITLE
process_publish_layer_target_tag_by_source_tag[PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_POSITION] \
    = PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_POSITION
process_publish_layer_target_tag_by_source_tag[PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_CRS] \
    = PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_CRS
process_publish_layer_target_tag_by_source_tag[PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_DATE] \
    = PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_DATE
process_publish_layer_target_tag_by_source_tag[PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_MINIMUM_ZOOM] \
    = PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_MINIMUM_ZOOM
process_publish_layer_target_tag_by_source_tag[PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_MAXIMUM_ZOOM] \
    = PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_MAXIMUM_ZOOM
process_publish_layer_target_tag_by_source_tag[PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_LAYER_STYLE] \
    = PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_LAYER_STYLE
process_publish_layer_target_tag_by_source_tag[PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_TYPE] \
    = PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_TYPE
process_publish_layer_target_tag_by_source_tag[PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_DESCRIPTION] \
    = PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_DESCRIPTION
process_publish_layer_target_tag_by_source_tag[PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_VISIBLE] \
    = PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_VISIBLE
process_publish_layer_target_tag_by_source_tag[PROCESS_FUNCTION_PUBLISH_LAYERS_SOURCE_TAG_GROUP_NAME] \
    = PROCESS_FUNCTION_PUBLISH_LAYERS_TARGET_TAG_GROUP_NAME

use_layer_style = None
group_name = None
